name: custom action to print python

on: [push, workflow_dispatch]

jobs:
 build-python:
  runs-on: ubuntu-latest
  
  steps:  
   - uses: actions/checkout@v3
   
   - name: Check current directory and contents
     run: pwd
     
   - name: hello-world-action
     uses: ./.github/actions/actionHelloWorld
   
   - name: install-python
     uses: actions/setup-python@v4
     with:
      python-version: 3.11.0-rc.1
      
   - name: print-line
     run: echo 'welcome to python'
