name: custom action to print python

on: [push, workflow-dispatch]

jobs:
  build-python
  -name: build python
  
  steps:
    -name: checkout
    -uses: actions/checkout@v3
    
    -name: install python
    uses: actions/setup-python@v4
    with:
      python-version:3.10
    
    -name: print line
    run: echo 'welcome to python'
